Fetching data from xml... Done
--- Logging error ---m url...
Traceback (most recent call last):
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 78, in _try_fetch_xml
    return urllib.request.urlopen(url, data=None, timeout=10)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "fetch_presences.py", line 34, in <module>
    presences = PresencesDataset().fetch(deputies, '01/02/2011', '01/01/2015')
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 53, in fetch
    'presence'
  File "/home/victor/.local/lib/python3.5/site-packages/pandas/core/frame.py", line 364, in __init__
    data = list(data)
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 62, in _all_presences
    xml = self._try_fetch_xml(10, url)
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 80, in _try_fetch_xml
    log.error("HTTP Error", err.code, "when loading URL", url)
Message: 'HTTP Error'
Arguments: (500, 'when loading URL', 'http://www.camara.leg.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasParlamentar?dataIni=01/02/2011&dataFim=01/01/2015&numMatriculaParlamentar=587')
2017-12-28 15:59:34,196 - root - INFO - Skipping [HTTP Status 500] http://www.camara.leg.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasParlamentar?dataIni=01/02/2011&dataFim=01/01/2015&numMatriculaParlamentar=587
--- Logging error ---
Traceback (most recent call last):
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 78, in _try_fetch_xml
    return urllib.request.urlopen(url, data=None, timeout=10)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "fetch_presences.py", line 34, in <module>
    presences = PresencesDataset().fetch(deputies, '01/02/2011', '01/01/2015')
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 53, in fetch
    'presence'
  File "/home/victor/.local/lib/python3.5/site-packages/pandas/core/frame.py", line 364, in __init__
    data = list(data)
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 62, in _all_presences
    xml = self._try_fetch_xml(10, url)
  File "/home/victor/.local/lib/python3.5/site-packages/serenata_toolbox/chamber_of_deputies/presences_dataset.py", line 80, in _try_fetch_xml
    log.error("HTTP Error", err.code, "when loading URL", url)
Message: 'HTTP Error'
Arguments: (500, 'when loading URL', 'http://www.camara.leg.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasParlamentar?dataIni=01/02/2011&dataFim=01/01/2015&numMatriculaParlamentar=624')
2017-12-28 16:16:26,600 - root - INFO - Skipping [HTTP Status 500] http://www.camara.leg.br/SitCamaraWS/sessoesreunioes.asmx/ListarPresencasParlamentar?dataIni=01/02/2011&dataFim=01/01/2015&numMatriculaParlamentar=624
Loading info from url... Done
Exporting data to csv... Done
